// <auto-generated />
using System;
using ChaleOnline.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChaleOnline.Infrastructure.Migrations
{
    [DbContext(typeof(ChaleOnlineDbContext))]
    [Migration("20260720174802_AddAdminIdentity")]
    partial class AddAdminIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChaleOnline.Domain.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaleId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChaleId");

                    b.ToTable("Avaliacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChaleId = 1,
                            Comentario = "Chalé impecável, exatamente como nas fotos.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 2,
                            ChaleId = 1,
                            Comentario = "Ótima localização e muito aconchegante.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 3,
                            ChaleId = 2,
                            Comentario = "Bom custo-benefício, voltaríamos com certeza.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 4,
                            ChaleId = 2,
                            Comentario = "Estrutura boa, mas o Wi-Fi falhou algumas vezes.",
                            Nota = 3
                        },
                        new
                        {
                            Id = 5,
                            ChaleId = 3,
                            Comentario = "Vista incrível, recomendo para casais.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 6,
                            ChaleId = 3,
                            Comentario = "Limpeza impecável e anfitrião muito atencioso.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 7,
                            ChaleId = 4,
                            Comentario = "Chalé impecável, exatamente como nas fotos.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 8,
                            ChaleId = 4,
                            Comentario = "Ótima localização e muito aconchegante.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 9,
                            ChaleId = 5,
                            Comentario = "Bom custo-benefício, voltaríamos com certeza.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 10,
                            ChaleId = 5,
                            Comentario = "Estrutura boa, mas o Wi-Fi falhou algumas vezes.",
                            Nota = 3
                        },
                        new
                        {
                            Id = 11,
                            ChaleId = 6,
                            Comentario = "Vista incrível, recomendo para casais.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 12,
                            ChaleId = 6,
                            Comentario = "Limpeza impecável e anfitrião muito atencioso.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 13,
                            ChaleId = 7,
                            Comentario = "Chalé impecável, exatamente como nas fotos.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 14,
                            ChaleId = 7,
                            Comentario = "Ótima localização e muito aconchegante.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 15,
                            ChaleId = 8,
                            Comentario = "Bom custo-benefício, voltaríamos com certeza.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 16,
                            ChaleId = 8,
                            Comentario = "Estrutura boa, mas o Wi-Fi falhou algumas vezes.",
                            Nota = 3
                        },
                        new
                        {
                            Id = 17,
                            ChaleId = 9,
                            Comentario = "Vista incrível, recomendo para casais.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 18,
                            ChaleId = 9,
                            Comentario = "Limpeza impecável e anfitrião muito atencioso.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 19,
                            ChaleId = 10,
                            Comentario = "Chalé impecável, exatamente como nas fotos.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 20,
                            ChaleId = 10,
                            Comentario = "Ótima localização e muito aconchegante.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 21,
                            ChaleId = 11,
                            Comentario = "Bom custo-benefício, voltaríamos com certeza.",
                            Nota = 4
                        },
                        new
                        {
                            Id = 22,
                            ChaleId = 11,
                            Comentario = "Estrutura boa, mas o Wi-Fi falhou algumas vezes.",
                            Nota = 3
                        },
                        new
                        {
                            Id = 23,
                            ChaleId = 12,
                            Comentario = "Vista incrível, recomendo para casais.",
                            Nota = 5
                        },
                        new
                        {
                            Id = 24,
                            ChaleId = 12,
                            Comentario = "Limpeza impecável e anfitrião muito atencioso.",
                            Nota = 4
                        });
                });

            modelBuilder.Entity("ChaleOnline.Domain.Chale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("NumeroBanheiros")
                        .HasColumnType("int");

                    b.Property<int>("NumeroQuartos")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Chale", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Pinheiro Bravo",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 420m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 2,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Trilha da Neblina",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 435m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 3,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Cabana do Vale",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 410m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 4,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Recanto da Araucária",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 445m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 5,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Clareira Dourada",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 425m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 6,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Refúgio do Riacho",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 430m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 7,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Vista da Serra",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 620m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 8,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Morada Alpina",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 635m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 9,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Chalé do Bosque",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 610m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 10,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Encosta Verde",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 645m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 11,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Grande Refúgio",
                            NumeroBanheiros = 2,
                            NumeroQuartos = 4,
                            Preco = 890m,
                            Tipo = "C"
                        },
                        new
                        {
                            Id = 12,
                            FotoUrl = "/media/pousada/deck-vista.jpg",
                            Nome = "Casa da Montanha",
                            NumeroBanheiros = 2,
                            NumeroQuartos = 4,
                            Preco = 910m,
                            Tipo = "C"
                        });
                });

            modelBuilder.Entity("ChaleOnline.Domain.ChaleComodidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaleId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ChaleId");

                    b.ToTable("ChaleComodidade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChaleId = 1,
                            Nome = "Lareira"
                        },
                        new
                        {
                            Id = 2,
                            ChaleId = 1,
                            Nome = "Deck com hidromassagem"
                        },
                        new
                        {
                            Id = 3,
                            ChaleId = 1,
                            Nome = "Vista para o bosque"
                        },
                        new
                        {
                            Id = 4,
                            ChaleId = 2,
                            Nome = "Deck com hidromassagem"
                        },
                        new
                        {
                            Id = 5,
                            ChaleId = 2,
                            Nome = "Vista para o bosque"
                        },
                        new
                        {
                            Id = 6,
                            ChaleId = 2,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 7,
                            ChaleId = 3,
                            Nome = "Vista para o bosque"
                        },
                        new
                        {
                            Id = 8,
                            ChaleId = 3,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 9,
                            ChaleId = 3,
                            Nome = "Estacionamento privativo"
                        },
                        new
                        {
                            Id = 10,
                            ChaleId = 4,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 11,
                            ChaleId = 4,
                            Nome = "Estacionamento privativo"
                        },
                        new
                        {
                            Id = 12,
                            ChaleId = 4,
                            Nome = "Churrasqueira"
                        },
                        new
                        {
                            Id = 13,
                            ChaleId = 5,
                            Nome = "Estacionamento privativo"
                        },
                        new
                        {
                            Id = 14,
                            ChaleId = 5,
                            Nome = "Churrasqueira"
                        },
                        new
                        {
                            Id = 15,
                            ChaleId = 5,
                            Nome = "Lareira"
                        },
                        new
                        {
                            Id = 16,
                            ChaleId = 6,
                            Nome = "Churrasqueira"
                        },
                        new
                        {
                            Id = 17,
                            ChaleId = 6,
                            Nome = "Lareira"
                        },
                        new
                        {
                            Id = 18,
                            ChaleId = 6,
                            Nome = "Deck com hidromassagem"
                        },
                        new
                        {
                            Id = 19,
                            ChaleId = 7,
                            Nome = "Lareira"
                        },
                        new
                        {
                            Id = 20,
                            ChaleId = 7,
                            Nome = "Deck com hidromassagem"
                        },
                        new
                        {
                            Id = 21,
                            ChaleId = 7,
                            Nome = "Vista para o bosque"
                        },
                        new
                        {
                            Id = 22,
                            ChaleId = 8,
                            Nome = "Deck com hidromassagem"
                        },
                        new
                        {
                            Id = 23,
                            ChaleId = 8,
                            Nome = "Vista para o bosque"
                        },
                        new
                        {
                            Id = 24,
                            ChaleId = 8,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 25,
                            ChaleId = 9,
                            Nome = "Vista para o bosque"
                        },
                        new
                        {
                            Id = 26,
                            ChaleId = 9,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 27,
                            ChaleId = 9,
                            Nome = "Estacionamento privativo"
                        },
                        new
                        {
                            Id = 28,
                            ChaleId = 10,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 29,
                            ChaleId = 10,
                            Nome = "Estacionamento privativo"
                        },
                        new
                        {
                            Id = 30,
                            ChaleId = 10,
                            Nome = "Churrasqueira"
                        },
                        new
                        {
                            Id = 31,
                            ChaleId = 11,
                            Nome = "Estacionamento privativo"
                        },
                        new
                        {
                            Id = 32,
                            ChaleId = 11,
                            Nome = "Churrasqueira"
                        },
                        new
                        {
                            Id = 33,
                            ChaleId = 11,
                            Nome = "Lareira"
                        },
                        new
                        {
                            Id = 34,
                            ChaleId = 12,
                            Nome = "Churrasqueira"
                        },
                        new
                        {
                            Id = 35,
                            ChaleId = 12,
                            Nome = "Lareira"
                        },
                        new
                        {
                            Id = 36,
                            ChaleId = 12,
                            Nome = "Deck com hidromassagem"
                        });
                });

            modelBuilder.Entity("ChaleOnline.Domain.ChaleMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaleId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ChaleId");

                    b.ToTable("ChaleMidia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChaleId = 1,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ChaleId = 1,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ChaleId = 1,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ChaleId = 1,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ChaleId = 1,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ChaleId = 1,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 7,
                            ChaleId = 2,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 8,
                            ChaleId = 2,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 9,
                            ChaleId = 2,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 10,
                            ChaleId = 2,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 11,
                            ChaleId = 2,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 12,
                            ChaleId = 2,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 13,
                            ChaleId = 3,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 14,
                            ChaleId = 3,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 15,
                            ChaleId = 3,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 16,
                            ChaleId = 3,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 17,
                            ChaleId = 3,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 18,
                            ChaleId = 3,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 19,
                            ChaleId = 4,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 20,
                            ChaleId = 4,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 21,
                            ChaleId = 4,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 22,
                            ChaleId = 4,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 23,
                            ChaleId = 4,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 24,
                            ChaleId = 4,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 25,
                            ChaleId = 5,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 26,
                            ChaleId = 5,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 27,
                            ChaleId = 5,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 28,
                            ChaleId = 5,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 29,
                            ChaleId = 5,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 30,
                            ChaleId = 5,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 31,
                            ChaleId = 6,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 32,
                            ChaleId = 6,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 33,
                            ChaleId = 6,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 34,
                            ChaleId = 6,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 35,
                            ChaleId = 6,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 36,
                            ChaleId = 6,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 37,
                            ChaleId = 7,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 38,
                            ChaleId = 7,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 39,
                            ChaleId = 7,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 40,
                            ChaleId = 7,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 41,
                            ChaleId = 7,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 42,
                            ChaleId = 7,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 43,
                            ChaleId = 8,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 44,
                            ChaleId = 8,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 45,
                            ChaleId = 8,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 46,
                            ChaleId = 8,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 47,
                            ChaleId = 8,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 48,
                            ChaleId = 8,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 49,
                            ChaleId = 9,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 50,
                            ChaleId = 9,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 51,
                            ChaleId = 9,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 52,
                            ChaleId = 9,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 53,
                            ChaleId = 9,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 54,
                            ChaleId = 9,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 55,
                            ChaleId = 10,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 56,
                            ChaleId = 10,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 57,
                            ChaleId = 10,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 58,
                            ChaleId = 10,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 59,
                            ChaleId = 10,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 60,
                            ChaleId = 10,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 61,
                            ChaleId = 11,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 62,
                            ChaleId = 11,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 63,
                            ChaleId = 11,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 64,
                            ChaleId = 11,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 65,
                            ChaleId = 11,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 66,
                            ChaleId = 11,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        },
                        new
                        {
                            Id = 67,
                            ChaleId = 12,
                            Ordem = 0,
                            Tipo = "Foto",
                            Url = "/media/pousada/deck-vista.jpg"
                        },
                        new
                        {
                            Id = 68,
                            ChaleId = 12,
                            Ordem = 1,
                            Tipo = "Foto",
                            Url = "/media/pousada/fachada-entrada.jpg"
                        },
                        new
                        {
                            Id = 69,
                            ChaleId = 12,
                            Ordem = 2,
                            Tipo = "Foto",
                            Url = "/media/pousada/sala-lareira.jpg"
                        },
                        new
                        {
                            Id = 70,
                            ChaleId = 12,
                            Ordem = 3,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-casal.jpg"
                        },
                        new
                        {
                            Id = 71,
                            ChaleId = 12,
                            Ordem = 4,
                            Tipo = "Foto",
                            Url = "/media/pousada/quarto-duplo.jpg"
                        },
                        new
                        {
                            Id = 72,
                            ChaleId = 12,
                            Ordem = 5,
                            Tipo = "Video",
                            Url = "/media/pousada/tour-virtual.mp4"
                        });
                });

            modelBuilder.Entity("ChaleOnline.Domain.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaleId")
                        .HasColumnType("int");

                    b.Property<Guid>("CodigoConsulta")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataCheckin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataCheckout")
                        .HasColumnType("date");

                    b.Property<string>("EmailHospede")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeHospede")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChaleId");

                    b.HasIndex("CodigoConsulta")
                        .IsUnique();

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("ChaleOnline.Domain.ReservaNoite", b =>
                {
                    b.Property<int>("ChaleId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("ChaleId", "Data");

                    b.HasIndex("Data");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaNoite", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8f2b1e2a-6f3a-4b8e-9a1c-2b6d7e9f0a11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1C4E7B2A-9D3F-4C6E-A1B8-5F2D9E0C7A33",
                            Email = "admin@chaleonline.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@CHALEONLINE.COM",
                            NormalizedUserName = "ADMIN@CHALEONLINE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC5rPBHLiKsnG+JIV8jUibtQFCBBtT8uB5kt9SkrIiOGwX12lDodaGf4NObffB2T+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7A1D9C3E-2F5B-4A6D-8E1C-3B9F0D2A4C61",
                            TwoFactorEnabled = false,
                            UserName = "admin@chaleonline.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChaleOnline.Domain.Avaliacao", b =>
                {
                    b.HasOne("ChaleOnline.Domain.Chale", null)
                        .WithMany()
                        .HasForeignKey("ChaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChaleOnline.Domain.ChaleComodidade", b =>
                {
                    b.HasOne("ChaleOnline.Domain.Chale", null)
                        .WithMany()
                        .HasForeignKey("ChaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChaleOnline.Domain.ChaleMidia", b =>
                {
                    b.HasOne("ChaleOnline.Domain.Chale", null)
                        .WithMany()
                        .HasForeignKey("ChaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChaleOnline.Domain.Reserva", b =>
                {
                    b.HasOne("ChaleOnline.Domain.Chale", null)
                        .WithMany()
                        .HasForeignKey("ChaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChaleOnline.Domain.ReservaNoite", b =>
                {
                    b.HasOne("ChaleOnline.Domain.Chale", null)
                        .WithMany()
                        .HasForeignKey("ChaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChaleOnline.Domain.Reserva", null)
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
