// <auto-generated />
using ChaleOnline.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChaleOnline.Infrastructure.Migrations
{
    [DbContext(typeof(ChaleOnlineDbContext))]
    [Migration("20260717233229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChaleOnline.Domain.Chale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("NumeroBanheiros")
                        .HasColumnType("int");

                    b.Property<int>("NumeroQuartos")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Chale", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FotoUrl = "/media/chales/tipo-a.svg",
                            Nome = "Pinheiro Bravo",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 420m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 2,
                            FotoUrl = "/media/chales/tipo-a.svg",
                            Nome = "Trilha da Neblina",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 435m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 3,
                            FotoUrl = "/media/chales/tipo-a.svg",
                            Nome = "Cabana do Vale",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 410m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 4,
                            FotoUrl = "/media/chales/tipo-a.svg",
                            Nome = "Recanto da Araucária",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 445m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 5,
                            FotoUrl = "/media/chales/tipo-a.svg",
                            Nome = "Clareira Dourada",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 425m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 6,
                            FotoUrl = "/media/chales/tipo-a.svg",
                            Nome = "Refúgio do Riacho",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 2,
                            Preco = 430m,
                            Tipo = "A"
                        },
                        new
                        {
                            Id = 7,
                            FotoUrl = "/media/chales/tipo-b.svg",
                            Nome = "Vista da Serra",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 620m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 8,
                            FotoUrl = "/media/chales/tipo-b.svg",
                            Nome = "Morada Alpina",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 635m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 9,
                            FotoUrl = "/media/chales/tipo-b.svg",
                            Nome = "Chalé do Bosque",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 610m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 10,
                            FotoUrl = "/media/chales/tipo-b.svg",
                            Nome = "Encosta Verde",
                            NumeroBanheiros = 1,
                            NumeroQuartos = 3,
                            Preco = 645m,
                            Tipo = "B"
                        },
                        new
                        {
                            Id = 11,
                            FotoUrl = "/media/chales/tipo-c.svg",
                            Nome = "Grande Refúgio",
                            NumeroBanheiros = 2,
                            NumeroQuartos = 4,
                            Preco = 890m,
                            Tipo = "C"
                        },
                        new
                        {
                            Id = 12,
                            FotoUrl = "/media/chales/tipo-c.svg",
                            Nome = "Casa da Montanha",
                            NumeroBanheiros = 2,
                            NumeroQuartos = 4,
                            Preco = 910m,
                            Tipo = "C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
